# Generated by Django 4.0.2 on 2022-02-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thermostat",
            name="name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.CreateModel(
            name="ThermostatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("triggered_at", models.TimeField(blank=True, null=True)),
                ("temperature", models.FloatField()),
                (
                    "thermostat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="triggers.thermostat",
                    ),
                ),
                (
                    "trigger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="triggers.trigger",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
