# Generated by Django 4.0.2 on 2022-02-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0002_alter_thermostat_name_thermostatlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="thermostatlog",
            name="no_op",
            field=models.BooleanField(default=False),
        ),
    ]
