# Generated by Django 4.0.2 on 2022-02-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0003_thermostatlog_no_op"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
