# Generated by Django 4.0.2 on 2022-02-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0005_rename_triggered_trigger_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
