# Generated by Django 4.0.2 on 2022-02-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0006_alter_trigger_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="recurring",
            field=models.BooleanField(default=False),
        ),
    ]
