# Generated by Django 4.0.2 on 2022-02-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0008_trigger_recur_on_friday_trigger_recur_on_monday_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trigger",
            name="recurring",
        ),
    ]
