# Generated by Django 4.0.2 on 2024-01-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0010_alter_trigger_recur_on_friday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thermostatlog',
            name='triggered_at',
        ),
    ]
